language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
  - rbx-19mode

# fast-stemmer is a C extension, so it won't work with JRuby ...
before_install: gem install bones; (gem install fast-stemmer &); sleep 10